# -*- coding: utf-8 -*-
"""Meteorological_data _analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vA_m5wmF8yJ_ymM4q0D9bDmkrMnfZnvU
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns
import sklearn as sk

data=pd.read_csv('/content/drive/MyDrive/weatherHistory.csv')

data

np.random.seed(0)

missing_values_count=data.isnull().sum()
missing_values_count[0:10]

total_cells=np.product(data.shape)
total_missing=missing_values_count.sum()
percent_missing=(total_missing/total_cells)*100
print(percent_missing)

data.info()

data.head()

col_for=["Formatted Date","Apparent Temperature (C)","Humidity"]
data=data[col_for]
data.head()

data['Formatted Date'] =pd.to_datetime(data['Formatted Date'],utc=True)
data =data.set_index('Formatted Date')
f_data=data[['Apparent Temperature (C)','Humidity']].resample('MS').mean()
f_data.head()

f_data

sns.pairplot(f_data,kind='scatter')
plt.show()

plt.figure(figsize =(16,6))
sns.relplot(x='Apparent Temperature (C)',y='Humidity',color='purple',hue_order="Summary"
,data=f_data)

plt.figure(figsize=(15,5));
plt.plot(f_data['Humidity'],label ='Humidity',color ='purple',linestyle ='dashed');
plt.plot(f_data['Apparent Temperature (C)'],label ='Apparent Temp',color ='green');
plt.title(' variation of apparent temperature v/s humidity',fontsize=23 );
plt.legend(loc=0,fontsize=12);
plt.xticks(fontsize =16);
plt.yticks(fontsize =14);



"""1) January : The graph of variation of Apparent Temperature and Humidity 
```

 
"""

Jan=f_data[f_data.index.month==1]
plt.figure(figsize=(15,5))
plt.plot(Jan.loc['2006-04-01':'2016-04-01','Apparent Temperature (C)'],marker='o',linestyle='-',label ='Apparent temp',color='green');
plt.plot(Jan.loc['2006-04-01':'2016-04-01','Humidity'],marker='o',linestyle='-',label ='Humidity',color='purple');
plt.legend(loc='center right',fontsize=10);
plt.xlabel('Month of January',fontsize=18);
plt.title('Humidity v/s Apparent Temperature',fontsize=23);

"""2)February : The graph of variation of Apparent Temperature and Humidity"""

Feb=f_data[f_data.index.month==2]
plt.figure(figsize=(15,5))
plt.plot(Feb.loc['2006-04-01':'2016-04-01','Apparent Temperature (C)'],marker='o',linestyle='-',label ='Apparent temp',color='green');
plt.plot(Feb.loc['2006-04-01':'2016-04-01','Humidity'],marker='o',linestyle='-',label ='Humidity',color='purple');
plt.legend(loc='center right',fontsize=10);
plt.xlabel('Month of February',fontsize=18);
plt.title('Humidity v/s Apparent Temperature',fontsize=23);

"""3) March : The graph of variation of Apparent temperature and Humidity"""

Mar=f_data[f_data.index.month==3]
plt.figure(figsize=(15,5))
plt.plot(Mar.loc['2006-04-01':'2016-04-01','Apparent Temperature (C)'],marker='o',linestyle='-',label ='Apparent temp',color='green');
plt.plot(Mar.loc['2006-04-01':'2016-04-01','Humidity'],marker='o',linestyle='-',label ='Humidity',color='purple');
plt.legend(loc='center right',fontsize=10);
plt.xlabel('Month of March',fontsize=18);
plt.title('Humidity v/s Apparent Temperature',fontsize=23);

"""4) April : The graph of variation of Apparent Temperature and Humidity"""

Apr=f_data[f_data.index.month==4]
plt.figure(figsize=(15,5))
plt.plot(Apr.loc['2006-04-01':'2016-04-01','Apparent Temperature (C)'],marker='o',linestyle='-',label ='Apparent temp',color='green');
plt.plot(Apr.loc['2006-04-01':'2016-04-01','Humidity'],marker='o',linestyle='-',label ='Humidity',color='purple');
plt.legend(loc='center right',fontsize=10);
plt.xlabel('Month of April',fontsize=18);
plt.title('Humidity v/s Apparent Temperature',fontsize=23);

"""5) May : The graph of variation of Apparent Temperature and Humidity"""

May=f_data[f_data.index.month==1]
plt.figure(figsize=(15,5))
plt.plot(May.loc['2006-04-01':'2016-04-01','Apparent Temperature (C)'],marker='o',linestyle='-',label ='Apparent temp',color='green');
plt.plot(May.loc['2006-04-01':'2016-04-01','Humidity'],marker='o',linestyle='-',label ='Humidity',color='purple');
plt.legend(loc='center right',fontsize=10);
plt.xlabel('Month of May',fontsize=18);
plt.title('Humidity v/s Apparent Temperature',fontsize=23);

"""6) June : The graph of variation of Apparent Temperature and Humidity"""

Jun=f_data[f_data.index.month==6]
plt.figure(figsize=(15,5))
plt.plot(Jun.loc['2006-04-01':'2016-04-01','Apparent Temperature (C)'],marker='o',linestyle='-',label ='Apparent temp',color='green');
plt.plot(Jun.loc['2006-04-01':'2016-04-01','Humidity'],marker='o',linestyle='-',label ='Humidity',color='purple');
plt.legend(loc='center right',fontsize=10);
plt.xlabel('Month of June',fontsize=18);
plt.title('Humidity v/s Apparent Temperature',fontsize=23);

"""7)July : The graph of variation of Apparent temperature and Humidity"""

Jul=f_data[f_data.index.month==7]
plt.figure(figsize=(15,5))
plt.plot(Jul.loc['2006-04-01':'2016-04-01','Apparent Temperature (C)'],marker='o',linestyle='-',label ='Apparent temp',color='green');
plt.plot(Jul.loc['2006-04-01':'2016-04-01','Humidity'],marker='o',linestyle='-',label ='Humidity',color='purple');
plt.legend(loc='center right',fontsize=10);
plt.xlabel('Month of July',fontsize=18);
plt.title('Humidity v/s Apparent Temperature',fontsize=23);

"""8)August : The graph of variation of Apparent Temperature and Humidity"""

Aug=f_data[f_data.index.month==8]
plt.figure(figsize=(15,5))
plt.plot(Aug.loc['2006-04-01':'2016-04-01','Apparent Temperature (C)'],marker='o',linestyle='-',label ='Apparent temp',color='green');
plt.plot(Aug.loc['2006-04-01':'2016-04-01','Humidity'],marker='o',linestyle='-',label ='Humidity',color='purple');
plt.legend(loc='center right',fontsize=10);
plt.xlabel('Month of August',fontsize=18);
plt.title('Humidity v/s Apparent Temperature',fontsize=23);

"""9) September : The graph of variation of Apparent Temperature and humidity"""

Sem=f_data[f_data.index.month==9]
plt.figure(figsize=(15,5))
plt.plot(Sem.loc['2006-04-01':'2016-04-01','Apparent Temperature (C)'],marker='o',linestyle='-',label ='Apparent temp',color='green');
plt.plot(Sem.loc['2006-04-01':'2016-04-01','Humidity'],marker='o',linestyle='-',label ='Humidity',color='purple');
plt.legend(loc='center right',fontsize=10);
plt.xlabel('Month of September',fontsize=18);
plt.title('Humidity v/s Apparent Temperature',fontsize=23);

"""10)October : The graph of variation of Apparent Temperature and Humidity"""

Oct=f_data[f_data.index.month==10]
plt.figure(figsize=(15,5))
plt.plot(Oct.loc['2006-04-01':'2016-04-01','Apparent Temperature (C)'],marker='o',linestyle='-',label ='Apparent temp',color='green');
plt.plot(Oct.loc['2006-04-01':'2016-04-01','Humidity'],marker='o',linestyle='-',label ='Humidity',color='purple');
plt.legend(loc='center right',fontsize=10);
plt.xlabel('Month of October',fontsize=18);
plt.title('Humidity v/s Apparent Temperature',fontsize=23);

"""11)November : The graph of Apparent Temperature and Humidity"""

Nov=f_data[f_data.index.month==11]
plt.figure(figsize=(15,5))
plt.plot(Nov.loc['2006-04-01':'2016-04-01','Apparent Temperature (C)'],marker='o',linestyle='-',label ='Apparent temp',color='green');
plt.plot(Nov.loc['2006-04-01':'2016-04-01','Humidity'],marker='o',linestyle='-',label ='Humidity',color='purple');
plt.legend(loc='center right',fontsize=10);
plt.xlabel('Month of November',fontsize=18);
plt.title('Humidity v/s Apparent Temperature',fontsize=23);

"""12)December : The graph of variation of Apparent Temperature and Humidity"""

Dec=f_data[f_data.index.month==12]
plt.figure(figsize=(15,5))
plt.plot(Dec.loc['2006-04-01':'2016-04-01','Apparent Temperature (C)'],marker='o',linestyle='-',label ='Apparent temp',color='green');
plt.plot(Dec.loc['2006-04-01':'2016-04-01','Humidity'],marker='o',linestyle='-',label ='Humidity',color='purple');
plt.legend(loc='center right',fontsize=10);
plt.xlabel('Month of December',fontsize=18);
plt.title('Humidity v/s Apparent Temperature',fontsize=23);

"""Conclusion :

As we can see in the above images . there are continuous changes in the temperature .we can see the ups and downs in the temperature . So , We can conclude that global warming has caused an uncertainty in the temperature over  past 10 years while the average humidity has remained constant throughout the 10 years.therefore this project analizing the data on the basis of given dataset and predicting on the cause of global warming on the basis of  variation in the temperature is the main cause whereas the humidity is somehow is the constant factor which is almost unchanged over past 10 years.it is average . 
"""

