# -*- coding: utf-8 -*-
"""ml_projects.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q4Bc-nUhBPbViO8sHJYfDY7Wm5khNLZe
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
# %matplotlib inline

df=pd.read_csv('/content/drive/MyDrive/gt2.csv')

df

df1 = df.dropna(axis=1)

df1

X = df1.iloc[:, [1,2]].values

from sklearn.cluster import DBSCAN
dbscan=DBSCAN(eps=2,min_samples=4)

model=dbscan.fit(X)

labels=model.labels_


from sklearn import metrics

fig = plt.figure(figsize=(10, 10))
sns.scatterplot(X[:,0], X[:,1], hue=["cluster-{}".format(x) for x in labels])

labels

sample_cores=np.zeros_like(labels,dtype=bool)

sample_cores[dbscan.core_sample_indices_]=True

sample_cores

n_clusters=len(set(labels))- (1 if -1 in labels else 0)

n_clusters

print(metrics.silhouette_score(X,labels))

fig = plt.figure(figsize=(20, 10))
fig.subplots_adjust(hspace=.5, wspace=.2)
i = 1
for x in range(10, 0, -1):
    eps = 1/(11-x)
    db = DBSCAN(eps=eps, min_samples=4).fit(X)
    core_samples_mask = np.zeros_like(db.labels_, dtype=bool)
    core_samples_mask[db.core_sample_indices_] = True
    labels = db.labels_
    
    print(eps)
    ax = fig.add_subplot(2, 5, i)
    ax.text(1, 4, "eps = {}".format(round(eps, 1)), fontsize=25, ha="center")
    sns.scatterplot(X[:,0], X[:,1], hue=["cluster-{}".format(x) for x in labels])
    
    i += 1